### ISSUE TITLE
Release Mockito 5

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#2802]
All right, the information is scattered throughout a couple of GitHub issues, but let's summarize the changes we want to make for Mockito 5:

- [x] Change default mockmaker to inline mockmaker (#2589)
- [x] Update minimum Java version to 11 (#2798)
- [x] Add `type()` method to `ArgumentMatcher` to fix vararg integration (#2807)
- [x] Remove internal `VarargsMatcher` (#2835)

I propose that we do not include any other breaking changes, as I think these two will already have a large impact. Since I would like our users to be able to upgrade to the latest version of Mockito, even with breaking changes, I think these bumps are already sufficiently large.

Please see the linked GitHub issues for a status update on what we need to do.

**Comment by TimvdLippe** [comment]
I wrote down the required steps for both issues in https://github.com/mockito/mockito/issues/2589#issuecomment-1328262373 and https://github.com/mockito/mockito/issues/2798#issuecomment-1328261554 Contributions welcome!

**Comment by big-andy-coates** [comment]
> I propose that we do not include any other breaking changes

... damn! I was about to suggest dropping the broken `VarargMatcher`.  Can we track that for Mokito 6? :)

**Comment by big-andy-coates** [comment]
Sounds like a plan. Just let me know.

**Comment by TimvdLippe** [comment]
Okay, we had some hiccups with the 4.10.0 release, but I just double-checked that all artifacts were published just fine to Maven Central. As such I will start the Mockito 5 release preparations by merging several PRs that will have breaking changes (FYI @mockito/developers ).

I would still like to keep our breaking changes list minimal if we can. Therefore, I propose that we keep the currently listed 2 and discuss the inclusion of the `VarargMatcher` removal, but we don't include any others. These we can do later in Mockito 6 in a year or so, to keep things flowing nicely.

**Comment by big-andy-coates** [comment]
Re: VarargMatcher,

https://github.com/mockito/mockito/issues/2807 fixes loads of vararg issues, but is NOT a breaking change.

Once #2807 is reviewed and merged, I'll raise a PR to remove VarargMatcher. Which will provide people with more context to discuss if it should / should not be included in this release.

**Comment by ramananrpn** [comment]
Hi would like to contribute here. Please let me know if any hand is needed

**Comment by big-andy-coates** [comment]
PR for the removal of `VarargMatcher` in progress: https://github.com/mockito/mockito/pull/2835

**Comment by TimvdLippe** [comment]
#2834 is passing all checks. I will start writing up a wiki page now with release notes that we can put on GitHub, similar to what we did with 4.0: https://github.com/mockito/mockito/releases/tag/v4.0.0

**Comment by TimvdLippe** [comment]
I have written up a draft on https://github.com/mockito/mockito/wiki/Draft-Mockito-5-release-notes @big-andy-coates can you please go over the draft and make sure the notes with regards to the varargs change makes sense?

Once we finalize the draft, we should also include this as a new section in the main `Mockito.class` JavaDoc (https://github.com/mockito/mockito/blob/c5d7fbc532301d003293649b71c8a6f87283638e/src/main/java/org/mockito/Mockito.java#L1667) so that we also include the full release notes in our artifacts. I think only the varargs release notes make sense to be included, the rest is general maintenance that is already available in our POM's.

**Comment by TimvdLippe** [comment]
Oh and @mockito/developers can you please review the draft release notes as well?

**Comment by raphw** [comment]
Thanks for the srite up. Looks good, I made some small changes!

**Comment by big-andy-coates** [comment]
> I have written up a draft on https://github.com/mockito/mockito/wiki/Draft-Mockito-5-release-notes @big-andy-coates can you please go over the draft and make sure the notes with regards to the varargs change makes sense?

Close enough.

You may want to consider simplifying the example issue to being unable to mock calls with exactly one vararg argument, as this may be easier to understand than overloaded methods.  Or you may want to include both the "unable to mock calls with exactly one argument" and the current issue about overloaded methods. Up to you.

Details of the "unable to mock calls with exactly one argument" issue:

For varargs methods, there was previously a way to only match zero arguments, or two or more arguments, by using the exact number of matchers, i.e.

```java
long call(String... args);

// Will match calls with exactly zero arguments:
when(mock.call()).thenReturn(0L);

// Will match calls with exactly two arguments:
when(mock.call(any(), any())).thenReturn(0L);
```

But following the pattern to match exactly one argument:

```java
when(mock.call(any())).thenReturn(0L);
```

doesn't work, as `any` is "vararg aware", so Mockito matches the `any` against _each element_ of the vararg parameter, meaning it will match any number of arguments, i.e. the above will match all of these:

```java
mock.call();
mock.call("a");
mock.call("a", "b");
```

With the new `type` method, its not possible to differentiate matching calls with any exact number of arguments, or to match any number of arguments.

```java
// Match any number of arguments:
when(mock.call(any(String[].class))).thenReturn(1L);
// Match invocations with no arguments:
when(mock.call()).thenReturn(1L);
// Match invocations with exactly one argument:
when(mock.call(any())).thenReturn(1L);
// Alternative to match invocations with exactly one argument:
when(mock.call(any(String.class))).thenReturn(1L);
// Match invocations with exactly two arguments:
when(mock.call(any(), any())).thenReturn(1L);
```

**Comment by TimvdLippe** [comment]
Cool, thanks @big-andy-coates I have updated the wiki page. Last step is to update the main Mockito documentation with a small section on the updates. I will probably get to that on Thursday

**Comment by TimvdLippe** [comment]
Hm, I was working on adding a section to the main Mockito JavaDoc, but I now think that we shouldn't do it. The breaking changes will be clearly documented on GitHub and we haven't included the breaking changes of Mockito 4 in the JavaDoc either. Therefore, I think we can ship Mockito 5 as-is. @raphw do you agree?

**Comment by raphw** [comment]
I also think it can be confusing in the javadoc. Most people will look there to see how things work now. Those are no release notes in that sense.-

**Comment by TimvdLippe** [comment]
Mockito 5 has been released: https://github.com/mockito/mockito/releases/tag/v5.0.0 Thanks everyone for your input, work and dedication!

**Comment by timtebeek** [comment]
Might also want to update the README, as that currently starts with

> ## Current version is 4.x
> Still on Mockito 1.x? See [what's new](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2) in Mockito 2! [Mockito 3](https://github.com/mockito/mockito/releases/tag/v3.0.0) does not introduce any breaking API changes, but now requires Java 8 over Java 6 for Mockito 2. [Mockito 4](https://github.com/mockito/mockito/releases/tag/v4.0.0) removes deprecated API.

**Comment by TimvdLippe** [comment]
@timtebeek good catch! Do you mind sending a PR to fix it?

**Comment by TWiStErRob** [comment]
@TimvdLippe I think you can unpin this.

**Comment by TimvdLippe** [comment]
@TWiStErRob I want to pin it for a bit, so that everybody can get the full context for the release. I will unpin this in a bit.
