### ISSUE TITLE
Announcement and release notes for 2.1.0 RC

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#582]
Also, let's make sure that release notes can be neatly generated for the RC. Needed for 2.0 release.

Checklist:
- [x] duplicate and unsorted committers - #598
- [x] grouping of improvements does not seem to work - #603
- [x] create announcement text and ensure it's on release checklist - #607

**Comment by bric3** [comment]
@szczepiq 2.0 tickets are managed via the milestone system of gh

**Comment by szczepiq** [comment]
Yes, I really like that we labeled the tickets with 2.0 milestone.

Do you envision releasing Mockito 2.0 with release notes linking to github milestone (e.g: https://github.com/mockito/mockito/milestone/1?closed=1)?

**Comment by bric3** [comment]
I don't know it is an idea.

**Comment by bric3** [comment]
@szczepiq The rest of the crew don't want to wait any longer for the RC. I propose that for this release candidate, we rely on the milestone view.

**Comment by szczepiq** [comment]
>@szczepiq The rest of the crew don't want to wait any longer for the RC.

I see :)

2.0.0 RC without announcement and clean release notes signals poor quality to the community. Are you happy to release poor quality for the sake of release? Is it really the voice of the entire crew?

Release notes for 2.0.0 can be automatically generated. We already have code that does it (hence this ticket). Essentially, removing release notes for all the beta versions, leaving last 1.10 stable should regenerate the release notes for all changes between 1.10 and 2.0.0-RC.1 (with nice groupings implemented by @szpak :). This should work, if there are some glitches I should be able to fix it quickly. After that we could add a paragraph with max 3 sentences that highlights the release.

Since everybody is anxious about RC going out, I'm happy to commit ETA on this ticket - end of this week (Sunday).

**Comment by szczepiq** [comment]
Tested the generation and there are 3 issues:
- [ ] - duplicate and unsorted committers
- [ ] - grouping of improvements does not seem to work

**Comment by szczepiq** [comment]
I drafted the announcement document here: https://github.com/mockito/mockito/blob/rc-release-notes-demo/doc/release-notes/official.md

Feedback needed!!! :)

**Comment by TimvdLippe** [comment]
I think this ticket can be closed?
