### ISSUE TITLE
Release process failed on 'bumpVersion' release step

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#915]
Mockito build failed on "bumpVersion" release step ([full log](https://travis-ci.org/mockito/mockito/jobs/196275405), [gist](https://gist.github.com/szczepiq/6fe5853d1f31585605c7ffe645347c69)).

### Root cause

"org.mockito.release-workflow" plugin ([GitHub repo](https://github.com/mockito/mockito-release-tools)) adds "incrementVersion" API method that Mockito uses for release automation. The method is available to users via: "project.versionFile.incrementVersion()" in the .gradle files. This method contains a bug: it does not work properly when the version declared in the file does not end with linebreak

### Actions

1. [x] Fix the Mockito 2.7.0 release (no release notes, no tag)
2. [x] Document steps to troubleshoot such problem with release pipeline, and steps to resolve - #916
3. [x] Report and fix bug in release-workflow plugin - [issue reported](https://github.com/mockito/mockito-release-tools/issues/1).
4. [x] Ensure Mockito uses latest version of release tools ["org.mockito.release-workflow" plugin](https://github.com/mockito/mockito-release-tools) - reported #917

**Comment by TimvdLippe** [comment]
This is a duplicate of #913

**Comment by szczepiq** [comment]
Hey @TimvdLippe, I didn't see the other issue reported. I'd prefer to keep this one open because it has more details.

**Comment by szczepiq** [comment]
BTW. thank you for fast reaction and reporting the issue :) I looking into it now.

**Comment by TimvdLippe** [comment]
Instead of reopening, you can add the details to the other issue. It does not make sense to keep 2 open

**Comment by szczepiq** [comment]
I would have to literally copy everything from this ticket to your original report, updating the title, description, etc. I'm not sure if it makes sense right now. I'm using this ticket as a work log. I'll close it once I finish.

**Comment by szczepiq** [comment]
Already fixed! Reference tickets will be worked on.
